name: Build and Upload Paper Artifact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Paper and Bukkit modules with Gradle
        run: ./gradlew :bukkit:build :paper:shadowJar

      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HuskHomes
          path: target/*.jar
